//! Metadata conventions shared by VFP designer files (SCX, VCX, FRX).

use chrono::{Datelike, Local, Timelike};
use std::sync::atomic::{AtomicU64, Ordering};

static SEQ: AtomicU64 = AtomicU64::new(0);

/// A 10-character identifier in the style of `SYS(2015)` ("_" + 9 base-36
/// characters), unique within this process and very unlikely to collide with
/// identifiers generated by VFP itself.
pub fn unique_id() -> String {
    const DIGITS: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);
    let seq = SEQ.fetch_add(1, Ordering::Relaxed);
    // 36^9 ≈ 1.0e14; mix time and a sequence number into that range.
    let mut n = (millis.wrapping_mul(1000).wrapping_add(seq % 1000)) % 101_559_956_668_416;
    let mut out = [b'0'; 9];
    for slot in out.iter_mut().rev() {
        *slot = DIGITS[(n % 36) as usize];
        n /= 36;
    }
    format!("_{}", String::from_utf8_lossy(&out))
}

/// Packed DOS-style timestamp used in the TIMESTAMP column of SCX/VCX/FRX.
pub fn fox_timestamp() -> f64 {
    let now = Local::now();
    let year = (now.year() - 1980).clamp(0, 127) as u64;
    let packed = (year << 25)
        | ((now.month() as u64) << 21)
        | ((now.day() as u64) << 16)
        | ((now.hour() as u64) << 11)
        | ((now.minute() as u64) << 5)
        | (now.second() as u64 / 2);
    packed as f64
}

/// Valid VFP object/member name: ASCII letter or underscore followed by
/// letters, digits or underscores, at most 128 characters.
pub fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && name.len() <= 128
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unique_ids_are_ten_chars_and_distinct() {
        let a = unique_id();
        let b = unique_id();
        assert_eq!(a.len(), 10);
        assert!(a.starts_with('_'));
        assert_ne!(a, b);
    }

    #[test]
    fn timestamp_fits_numeric_10() {
        assert!(fox_timestamp() < 9_999_999_999.0);
    }

    #[test]
    fn validates_names() {
        assert!(is_valid_name("txtName_1"));
        assert!(!is_valid_name("1abc"));
        assert!(!is_valid_name("a b"));
        assert!(!is_valid_name(""));
    }
}
